# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c0f901c9ab058c4adf59a99f857aaa63355d25aad3cd12fc095e576a55404d337429a513c6a82675a1f577dc82435df3c598c846b82962d6da8ed1b83e3f51

test:
  secret_key_base: 5c076accbf7f7a0f814a987dca497f93a55096f062db4c81b41fd87f2f1f5639e831ed7626ccb6789a839f540a5371ad45800e79885e7b41b643d7a78c1bda16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
